services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: review-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports: ["5433:5432"]

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: config-server
    environment:
      SERVER_PORT: "8888"
      SPRING_APPLICATION_NAME: "config-server"
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/nohpedro/config-swipe"
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: "main"
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8888/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 30

  eureka:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SERVER_PORT: "8762"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    ports:
      - "8762:8762"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8762/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 30

  gateway:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: gateway
    depends_on:
      eureka:
        condition: service_healthy
    environment:
      SERVER_PORT: "8082"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8762/eureka/"
      EUREKA_INSTANCE_HOSTNAME: "gateway"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
    ports:
      - "8082:8082"

  swipe-service:
    build:
      context: .
      dockerfile: Swipe-service/Dockerfile
    depends_on:
      postgres:
        condition: service_started
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SERVER_PORT: "8081"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    ports: ["8081:8081"]

volumes:
  pgdata:
