services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: review-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ================== CONFIG SERVER ==================
  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    container_name: config-server
    environment:
      SERVER_PORT: "8888"                           # puerto interno del micro
      SPRING_APPLICATION_NAME: "config-server"
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/ElNegis/cat-tinder-config-repo"
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: "main"
    ports:
      - "8888:8888"                                # EXTERNO:INTERNO
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8888/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 30

  eureka:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka
    environment:
      SERVER_PORT: "8762"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    ports:
      - "8762:8762"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8762/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 30

  gateway:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: gateway
    depends_on:
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SERVER_PORT: "18082"  # <-- igual que el puerto interno que exponemos
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8762/eureka/"
      EUREKA_INSTANCE_HOSTNAME: "gateway"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    ports:
      - "18082:18082"

  swipe-service:
    build:
      context: .
      dockerfile: Swipe-service/Dockerfile
    container_name: swipe-service
    depends_on:
      postgres:
        condition: service_started
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SERVER_PORT: "18081"  # <-- igual que el puerto interno que exponemos
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/review-db"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8762/eureka/"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    ports:
      - "18081:18081"

  config-ms:
    build:
      context: .
      dockerfile: confg-ms/Dockerfile
    container_name: config-ms
    depends_on:
      postgres:
        condition: service_started
      eureka:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SERVER_PORT: "18083"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/review-db"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8762/eureka/"
      SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
    ports:
      - "18083:18083"

volumes:
  pgdata:
