spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  cloud:
    config:
      username: ${CONFIG_SERVER_USER:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}
      label: ${CONFIG_SERVER_LABEL:main}
      profile: ${CONFIG_SERVER_PROFILE:default}

management:
  endpoints:
    web:
      exposure:
        include: health,info



