server:
  port: 8083

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tinder-realm
          jwk-set-uri: http://localhost:8080/realms/tinder-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, OK

      routes:
        # ==== API del Swipe Service ====
        - id: swipe-service
          uri: lb://SWIPE-SERVICE
          predicates:
            - Path=/swipe-service/**
          filters:
            - StripPrefix=1

        # ==== OpenAPI/Swagger del SwipeService (proxy) ====
        - id: swipe-service-openapi
          uri: lb://SWIPE-SERVICE
          predicates:
            - Path=/swipe-service/v3/api-docs/**, /swipe-service/swagger-ui.html, /swipe-service/swagger-ui/**, /swipe-service/webjars/**, /swipe-service/swagger-resources/**
          filters:
            - StripPrefix=1

        - id: confg-ms
          uri: lb://CONFG-MS
          predicates:
            - Path=/confg-ms/**
          filters:
            - StripPrefix=1

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://127.0.0.1:3000"
              - "http://localhost:5174"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - name: SwipeService
        url: /swipe-service/v3/api-docs
    disable-swagger-default-url: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,httpexchanges
  endpoint:
    health:
      show-details: always
