services:
  postgres:
    image: postgres:16-alpine
    ports: ["5433:5432"]
    environment:
      - POSTGRES_DB=review-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d   # <â€” nuevo
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U admin -d review-db'"]
      interval: 5s
      timeout: 3s
      retries: 60
volumes:
  pgdata:
